### ISSUE TITLE
test partitionVCs() on better cases 

### ISSUE THREAD

**Issue by dtwelch** [ClemsonRSRG/resolve-lite#37]
Not convinced at all this method is fully correct.

**Comment by Welchd1** [comment]
Here's two more test cases:  

```
(P => (Q /\ R)) 
--------------------- which produces:
1. P => Q
2. P => R
```
and

```
(P => (Pre /\ (Post => (Q /\ R))) 
--------------------- which produces:
1. P => Pre
2. P and Post => Q
3. P and Post => R
```

**Comment by Welchd1** [comment]
More tests for this added. There's a prelim recursive version added now of this that I *think* is working 

(at least working as expected w.r.t. the tests so far -- meaning the answers are in line with those returned by HK Harton's version)

**Comment by dtwelch** [comment]
No longer needed with the introduction of sequents and the (`Sequent_Form`) operator into vc-generation. Solves this very nicely.
