### ISSUE TITLE
grammatically: is an incoming sym allowed to prefix a function application?

### ISSUE THREAD

**Issue by dtwelch** [ClemsonRSRG/resolve-lite#40]
If not, this seems like it would be fairly easy to restrict grammatically..

**Comment by Welchd1** [comment]
Learned today that there's more to the `remember` rule than meets the eye. Turns out you can have multiple @@@ (incoming) signs stacked on a single variable depending on how users apply the remember rule... ... the more you know I guess.

**Comment by Welchd1** [comment]
yep. Consider ceramic array ensures for swap_element:
```
ensures e = @A(i) and A = lambda (j : Z).(
                        {{@e if j = i; @A(j) otherwise;}});
```
here `A(i)` is clearly a function application and is marked by `@`

**Comment by dtwelch** [comment]
Don't care anymore. Closed.
