### ISSUE TITLE
Unit test gencode and core libs

### ISSUE THREAD

**Issue by dtwelch** [ClemsonRSRG/resolve-lite#45]
due to the recent aliasing problems I've been encountering in generated code (for instance, #44), we should def. be testing output of translator and exercise swapping, and assignment of ints booleans, strings, characters, etc.

**Comment by Welchd1** [comment]
More progress with this since the last message was posted. Still need to write some tests for our ceramic array template-ops.

**Comment by Welchd1** [comment]
getting back to this now, going to start with symtab stuff though probably

**Comment by dtwelch** [comment]
Again: Like the VC generator. The code generator is likely going to be an evolving beast as the examples get more and more complicated. So hold off on this.
